services:
  - type: web
    plan: free
    name: config
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: True

